(function(){
    var language = {
        chinese: {
            name: "姓名",
            cellphone: "手机",
            company: "公司",
            title: "职位",
            email: "邮箱",
            signin: "签到",
            modal_confirm_1: "请选择您要报名的场次",
            modal_confirmText:"确定",
            modal_signin_1:"签到成功",
            modal_signin_2: "点击确定返回首页",
            modal_signin_3: "请选择签到的场次",
            modal_setup_1: "修改成功",
            modal_signup_1: "报名成功",
            modal_signup_2: "当前选择的场次今日报名人数已满，请选择其它场次",
            modal_signup_3: "请选择您要报名的场次",
            modal_signup_4: "请填写完整您的个人信息",
            
            index_1: "待参加的活动",
            index_2: "暂无待参加的活动",
            index_3: "活动",
            // index_4: "签到",
            index_5: "手工",
            index_6: "我的",
            
            confirm_1: "请确认您的个人信息：",
            // confirm_2: "姓名",
            // confirm_3: "手机",
            confirm_4: "未找到可参加的场次",
            confirm_5: "请选择确认参加的场次：",
            confirm_6: "请输入您的电话号码：",
            confirm_7: "请填写您的常用手机号码",
            confirm_8: "如遇问题，请联系活动主办方工作人员",
            confirm_9: "确认参加",
            confirm_10: "身份验证",
            
            details_1: "地图导航",
            details_2: "现场签到",
            details_3: "请于活动当天，将此二维码展示给现场负责签到的工作人员进行扫码，以完成签到。",
            
            employee_1: "工作人员绑定",
            // employee_2: "姓名",
            employee_3: "请填写您的真实姓名",
            // employee_4: "手机",
            employee_5: "请填写您的手机号码",
            employee_6: "确认绑定",
            
            list_1: "待参加",
            list_2: "待评价",
            list_3: "全部活动",
            list_4: "暂无活动",
            
            setup_1: "修改个人信息",
            // setup_2: "姓名",
            setup_3: "英文名",
            // setup_4: "手机",
            // setup_5: "公司",
            // setup_6: "职位",
            // setup_7: "邮箱",
            setup_8: "性别",
            setup_9: "生日",
            setup_10: "保存",
            
            // signin_1: "签到",
            signin_2: "未找到嘉宾的个人信息",
            // signin_3: "姓名",
            // signin_4: "手机",
            // signin_5: "公司",
            // signin_6: "职位",
            signin_7: "未找到可签到的场次信息",
            signin_8: "请勾选嘉宾确认签到的场次：",
            signin_9: "请填写嘉宾的常用手机号来读取嘉宾的个人信息",
            // signin_10: "手机",
            signin_11: "请填写嘉宾的手机号码",
            signin_12: "确认签到",
            signin_13: "身份验证",
            
            signup_1: "请填写您的个人信息：",
            // signup_2: "手机",
            signup_3: "请填写您的常用手机号码",
            // signup_4: "姓名",
            signup_5: "请填写您的姓名",
            // signup_6: "邮箱",
            signup_7: "请填写您的常用邮箱",
            signup_8: "如遇问题，请联系活动主办方工作人员",
            signup_9: "确认报名",

            user_1: "点击修改个人信息",
            user_2: "待参加",
            user_3: "待评价",
            user_4: "全部活动",


        },
        english: {
            name: "Name",
            cellphone: "Cellphone",
            company: "Company",
            title: "Title",
            email: "E-mail",
            signin: "Sign up",
            modal_confirmText: "Ok",
            modal_confirm_1: "Please select session : ",
            modal_signin_1: "Successful",
            modal_signin_2: "Click confirm to return",
            modal_signin_3: "Please select session",
            modal_setup_1: "Changes Saved",
            modal_signup_1: "Successful",
            modal_signup_2: "Your current selected session is full，please select another",
            modal_signup_3: "Please select session",
            modal_signup_4: "Please fill in your personal information",

            index_1: "Available event",
            index_2: "No available event",
            index_3: "Events",
            // index_4: "签到",
            index_5: "Manual",
            index_6: "Me",

            confirm_1: "Please confirm your personal information : ",
            // confirm_2: "姓名",
            // confirm_3: "手机",
            confirm_4: "Invitation cannot be found",
            confirm_5: "Please select session : ",
            confirm_6: "Please fill in your phone no.",
            confirm_7: "Please fill in your commonly used phone no.",
            confirm_8: "Contact us if you encounter any problems",
            confirm_9: "Confirm",
            confirm_10: "Authentication",

            details_1: "Map navigation",
            details_2: "QR Code",
            details_3: "To complete the sign-up process, please show this QR code to on-site staff for scanning.",

            employee_1: "Staff Binding",
            // employee_2: "姓名",
            employee_3: "Your name",
            // employee_4: "手机",
            employee_5: "Mobile phone",
            employee_6: "Confirm binding",

            list_1: "Events to be attended",
            list_2: "Events to be reviewed",
            list_3: "All events",
            list_4: "No event",

            setup_1: "Alter your personal information",
            // setup_2: "姓名",
            setup_3: "EnglishName",
            // setup_4: "手机",
            // setup_5: "公司",
            // setup_6: "职位",
            // setup_7: "邮箱",
            setup_8: "Sex",
            setup_9: "Birthday",
            setup_10: "Save",

            // signin_1: "签到",
            signin_2: "Information cannot be found",
            // signin_3: "姓名",
            // signin_4: "手机",
            // signin_5: "公司",
            // signin_6: "职位",
            signin_7: "Invitation cannot be found",
            signin_8: "Please select session",
            signin_9: "Please fill in guest's phone no. to access guest's information",
            // signin_10: "手机",
            signin_11: "Please fill in guest's phone no.",
            signin_12: "Confirm",
            signin_13: "Authentication",

            signup_1: "Please fill in your personal information",
            // signup_2: "手机",
            signup_3: "Mobile phone",
            // signup_4: "姓名",
            signup_5: "Your name",
            // signup_6: "邮箱",
            signup_7: "E-mail address",
            signup_8: "Contact us if you encounter any problems",
            signup_9: "Confirm",

            user_1: "Click to alter your information",
            user_2: "Events to be attended",
            user_3: "Events to be reviewed",
            user_4: "All events",
        }
    }
    module.exports = { language }
}())